### ISSUE TITLE
Ngrams should be overlapping

### ISSUE THREAD

**Issue by mackenzieyoung** [filontheroad/murder-mystery#2]
This is an interesting way of doing this...unfortunately it doesn't quite work.

The ngrams outputted from your ngram_creator function should be pairs of overlapping words, like ["you may", "may call", "call me" ...]. No need to check for even indices with `if counter % 2 != 0`, also, your for loop does not need to increase `counter`, it does that automatically. The code below is simpler and produces the correct output:

```
def ngram_creator(text_list):
    two_n_gram = []
    counter = 0
    for counter in range(0,len(text_list)-1):
        two_n_gram.append((text_list[counter]+ " " + text_list[counter+1]))
    return two_n_gram
```

**Comment by filontheroad** [comment]
Ah I see my mistake. Perfect. Thanks
